services:
  zk_service:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk_container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka_service:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_container
    depends_on:
      - zk_service
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zk_service:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka_broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    expose:
      - "9092"

  postgres_db:
    image: postgres:16.2-alpine3.19
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./secrets
    ports:
      - "54321:5432"
    networks:
      - app_network
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      POSTGRES_DB: kafka_database

  pgadmin_tool:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - ./secrets2
    ports:
      - "6080:80"
    networks:
      - app_network
    links:
      - postgres_db

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge
